# Application bindings
exec-once = hyprctl dispatch renameworkspace 11 "music"
exec-once = hyprctl dispatch renameworkspace 12 "chatgpt"
exec-once = hyprctl dispatch renameworkspace 13 "obsidian"
exec-once = hyprctl dispatch renameworkspace 14 "chat"

$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

bindd = SUPER, B, Browser, exec, $browser
bindd = SUPER, M, Music, exec, $HOME/.local/bin/youtube-music.sh
bindd = SUPER, N, Editor, exec, $HOME/.local/bin/editor-terminal.sh
bindd = SUPER, O, Obsidian, exec,  $HOME/.local/bin/obsidian.sh
bindd = SUPER, A, ChatGPT, exec, $HOME/.local/bin/chatgpt.sh

unbind = SUPER, T #Remove binding for toggle floating
bindd = SUPER SHIFT, T, Toggle floating, togglefloating
bindd = SUPER, T, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"

unbind = SUPER, F
bindd = SUPER SHIFT, F, Full screen, fullscreen
bindd = SUPER, F, File manager, exec, uwsm app -- nautilus --new-window
