[/]
move-to-center=['<Super>c']
move-to-workspace-1=['<Super><Shift>h']
move-to-workspace-2=['<Super><Shift>semicolon']
move-to-workspace-3=['<Super><Shift>Colon']
move-to-workspace-4=['<Super><Shift>n']
move-to-workspace-5=['<Super><Shift>e']
move-to-workspace-6=['<Super><Shift>i']
move-to-workspace-7=['<Super><Shift>l']
move-to-workspace-8=['<Super><Shift>u']
move-to-workspace-9=['<Super><Shift>y']
switch-to-workspace-1=['<Super>h']
switch-to-workspace-2=['<Super>Comma']
switch-to-workspace-3=['<Super>Period']
switch-to-workspace-4=['<Super>n']
switch-to-workspace-5=['<Super>e']
switch-to-workspace-6=['<Super>i']
switch-to-workspace-7=['<Super>l']
switch-to-workspace-8=['<Super>u']
switch-to-workspace-9=['<Super>y']
