# Background and foreground colors
background = #fefaf5
foreground = #141117

# Standard colors
palette = 0=#fefaf5
palette = 1=#95655e
palette = 2=#57774a
palette = 3=#886546
palette = 4=#7f6a85
palette = 5=#9e597c
palette = 6=#327a7a
palette = 7=#141117

# Bright colors
palette = 8=#8f8b85
palette = 9=#be877e
palette = 10=#769d60
palette = 11=#b0885f
palette = 12=#a58caf
palette = 13=#c978a5
palette = 14=#50a09f
palette = 15=#312d35
