$color = rgba(254, 250, 245, 1)
$inner_color = rgba(254, 250, 245, 0.66)
$outer_color = rgba(158, 89, 124, 1)
$font_color = rgba(20, 17, 23, 1)
$placeholder_color = rgba(20, 17, 23, 0.7)
$check_color = rgba(50, 122, 122, 1)
