background            #fefaf5
foreground            #141117

# black
color0  #fefaf5
color8  #8f8b85

# red
color1  #95655e
color9  #be877e

# green
color2  #57774a
color10 #769d60

# yellow
color3  #886546
color11 #b0885f

# blue
color4  #7f6a85
color12 #a58caf

# magenta
color5  #9e597c
color13 #c978a5

#cyan
color6  #327a7a
color14 #50a09f

#white
color7  #141117
color15 #312d35


