# Background and foreground colors
background = #010112
foreground = #FAE4EF

# Standard colors
palette = 0=#010112
palette = 1=#996b6d
palette = 2=#57846f
palette = 3=#927f58
palette = 4=#7e89b0
palette = 5=#a688a9
palette = 6=#70a7b2
palette = 7=#FAE4EF

# Bright colors
palette = 8=#606167
palette = 9=#c28d8f
palette = 10=#57977a
palette = 11=#a78d56
palette = 12=#8897cc
palette = 13=#bc92c0
palette = 14=#6cbac9
palette = 15=#faf7fe
