$color = rgba(1, 1, 18, 1)
$inner_color = rgba(1, 1, 18, 0.66)
$outer_color = rgba(166, 136, 169, 1)
$font_color = rgba(250, 228, 239, 1)
$placeholder_color = rgba(250, 228, 239, 0.7)
$check_color = rgba(112, 167, 178, 1)
