background            #010112
foreground            #FAE4EF

# black
color0  #010112
color8  #606167

# red
color1  #996b6d
color9  #c28d8f

# green
color2  #57846f
color10 #57977a

# yellow
color3  #927f58
color11 #a78d56

# blue
color4  #7e89b0
color12 #8897cc

# magenta
color5  #a688a9
color13 #bc92c0

#cyan
color6  #70a7b2
color14 #6cbac9

#white
color7  #FAE4EF
color15 #faf7fe


